### ISSUE TITLE
Garmin inReach MINI 2 unit_id command non-standard response

### ISSUE THREAD

**Issue by nuclearcat** [quentinsf/pygarmin#14]
Hi! While just testing pygarmin on my device noticed following issue:
```
pygarmin -p /dev/ttyUSB2 -D info
Version 2.0.2
2024-08-03 14:11:13,326 Version 2.0.2
Listening on port /dev/ttyUSB2
2024-08-03 14:11:13,326 Listening on port /dev/ttyUSB2
Request product data...
2024-08-03 14:11:13,326 Request product data...
Pack packet...
2024-08-03 14:11:13,326 Pack packet...
Packet data size: 0
2024-08-03 14:11:13,326 Packet data size: 0
Packet data checksum: 2
2024-08-03 14:11:13,326 Packet data checksum: 2
< 10 fe 00 02 10 03
2024-08-03 14:11:13,327 < 10 fe 00 02 10 03
Read ACK/NAK
2024-08-03 14:11:13,327 Read ACK/NAK
> 10 06 02 fe 00 fa 10 03
2024-08-03 14:11:13,327 > 10 06 02 fe 00 fa 10 03
Unpack packet...
2024-08-03 14:11:13,327 Unpack packet...
Received ACK packet
2024-08-03 14:11:13,327 Received ACK packet
Expect product data
2024-08-03 14:11:13,327 Expect product data
> 10 ff 1e 80 0f a6 01 49 4e 52 45 41 43 48 20 4d 49 4e 49 20 32 20 53 59 53 20 56 30 34 2e 32 32 00 89 10 03
2024-08-03 14:11:13,327 > 10 ff 1e 80 0f a6 01 49 4e 52 45 41 43 48 20 4d 49 4e 49 20 32 20 53 59 53 20 56 30 34 2e 32 32 00 89 10 03
Unpack packet...
2024-08-03 14:11:13,327 Unpack packet...
Send ACK packet
2024-08-03 14:11:13,327 Send ACK packet
Pack packet...
2024-08-03 14:11:13,327 Pack packet...
Packet data size: 2
2024-08-03 14:11:13,327 Packet data size: 2
Packet data checksum: 249
2024-08-03 14:11:13,327 Packet data checksum: 249
< 10 06 02 ff 00 f9 10 03
2024-08-03 14:11:13,327 < 10 06 02 ff 00 f9 10 03
Product ID: 3968
2024-08-03 14:11:13,327 Product ID: 3968
Software version: 422.00
2024-08-03 14:11:13,327 Software version: 422.00
Product description: INREACH MINI 2 SYS V04.22
2024-08-03 14:11:13,327 Product description: INREACH MINI 2 SYS V04.22
Get supported protocols and data types...
2024-08-03 14:11:13,327 Get supported protocols and data types...
Read protocols using Protocol Capability Protocol
2024-08-03 14:11:13,328 Read protocols using Protocol Capability Protocol
> 10 fd 0f 50 00 00 4c 01 00 41 0a 00 41 87 03 41 1a 04 e2 10 03
2024-08-03 14:11:13,328 > 10 fd 0f 50 00 00 4c 01 00 41 0a 00 41 87 03 41 1a 04 e2 10 03
Unpack packet...
2024-08-03 14:11:13,328 Unpack packet...
Send ACK packet
2024-08-03 14:11:13,328 Send ACK packet
Pack packet...
2024-08-03 14:11:13,328 Pack packet...
Packet data size: 2
2024-08-03 14:11:13,328 Packet data size: 2
Packet data checksum: 251
2024-08-03 14:11:13,328 Packet data checksum: 251
< 10 06 02 fd 00 fb 10 03
2024-08-03 14:11:13,328 < 10 06 02 fd 00 fb 10 03
Parse supported protocols and datatypes...
2024-08-03 14:11:13,328 Parse supported protocols and datatypes...
Got physical protocol 'P000'. Ignoring...
2024-08-03 14:11:13,328 Got physical protocol 'P000'. Ignoring...
Got link protocol 'L001'. Adding...
2024-08-03 14:11:13,328 Got link protocol 'L001'. Adding...
Got application protocol 'A010'. Adding...
2024-08-03 14:11:13,328 Got application protocol 'A010'. Adding...
Got application protocol 'A903'. Adding...
2024-08-03 14:11:13,328 Got application protocol 'A903'. Adding...
Got application protocol 'A1050'. Adding...
2024-08-03 14:11:13,328 Got application protocol 'A1050'. Adding...
Supported protocols and data types: [['L001'], ['A010'], ['A903'], ['A1050']]
2024-08-03 14:11:13,328 Supported protocols and data types: [['L001'], ['A010'], ['A903'], ['A1050']]
Register protocol L001.
2024-08-03 14:11:13,328 Register protocol L001.
Register protocol A010.
2024-08-03 14:11:13,328 Register protocol A010.
Ignore undocumented protocol A903.
2024-08-03 14:11:13,328 Ignore undocumented protocol A903.
Ignore undocumented protocol A1050.
2024-08-03 14:11:13,328 Ignore undocumented protocol A1050.
Registered protocols and data types: {'link_protocol': [<class 'pygarmin.protocol.L001'>], 'device_command_protocol': [<class 'pygarmin.protocol.A010'>]}
2024-08-03 14:11:13,328 Registered protocols and data types: {'link_protocol': [<class 'pygarmin.protocol.L001'>], 'device_command_protocol': [<class 'pygarmin.protocol.A010'>]}
Create protocol link_protocol...
2024-08-03 14:11:13,328 Create protocol link_protocol...
Request Product Id...
2024-08-03 14:11:13,328 Request Product Id...
Create protocol device_command_protocol...
2024-08-03 14:11:13,328 Create protocol device_command_protocol...
Pack packet...
2024-08-03 14:11:13,328 Pack packet...
Packet data size: 2
2024-08-03 14:11:13,328 Packet data size: 2
Packet data checksum: 230
2024-08-03 14:11:13,328 Packet data checksum: 230
< 10 0a 02 0e 00 e6 10 03
2024-08-03 14:11:13,328 < 10 0a 02 0e 00 e6 10 03
Read ACK/NAK
2024-08-03 14:11:13,328 Read ACK/NAK
> 10 f8 0e 47 50 53 20 56 30 37 2e 30 30 2e 30 30 00 17 10 03
2024-08-03 14:11:13,328 > 10 f8 0e 47 50 53 20 56 30 37 2e 30 30 2e 30 30 00 17 10 03
Unpack packet...
2024-08-03 14:11:13,328 Unpack packet...
Packet ID: 248 expected pid: 10 received pid: 3817862919306180117607895748679
Traceback (most recent call last):
  File "/home/nuclearcat/.local/bin/pygarmin", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nuclearcat/.local/lib/python3.12/site-packages/pygarmin/pygarmin.py", line 1509, in main
    command(args)
  File "/home/nuclearcat/.local/lib/python3.12/site-packages/pygarmin/pygarmin.py", line 250, in info
    info += f"Unit ID: {self.gps.unit_id}\n"
                        ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/nuclearcat/.local/lib/python3.12/site-packages/pygarmin/garmin.py", line 373, in unit_id
    self.link.send_packet(self.link.pid_command_data,
  File "/home/nuclearcat/.local/lib/python3.12/site-packages/pygarmin/protocol.py", line 27, in send_packet
    self.phys.send_packet(pid, data)
  File "/home/nuclearcat/.local/lib/python3.12/site-packages/pygarmin/link.py", line 235, in send_packet
    self.read_ack(pid)
  File "/home/nuclearcat/.local/lib/python3.12/site-packages/pygarmin/link.py", line 265, in read_ack
    raise mod_error.GarminError("Received neither ACK nor NAK packet")
pygarmin.error.GarminError: 'Received neither ACK nor NAK packet'
```

Based on data i saw, it seems that when undocumented command is issued, device doesn't send ACK/NAK, but directly gives answer with data ("GPS V07.00.00")
I am willing to contribute, if it is necessary, but what will be best solution?
1)Just ignore unit_id on this unit
2)Make for L000 optional parameter acknowledge, which by default true, but can be set False (don't expect ACK/NAK), and use it for this specific product_id (inreach mini 2).
3)Just not worth to bother :)

**Comment by fvdbeek** [comment]
I will look into it. Because I don't own this device, it is probably the safest and definitely the easiest solution to ignore the unit ID when requesting the product info and provide an own sub-command for the unit ID (that of course will raise an error with your device).
