### ISSUE TITLE
Question: What can be done?

### ISSUE THREAD

**Issue by R1BGW** [quentinsf/pygarmin#15]
Good afternoon. Using your library, I wrote a small utility for exchanging data with GPS devices. Problem: I can't send the track, it gives an error : C:\Users\AME>pygarmin -p COM6 put-tracks -t gpx  C:\Users\AME\Desktop\трек.gpx
C:\Users\AME\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygarmin\gpx.py:1040: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if extension:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\AME\AppData\Local\Programs\Python\Python312\Scripts\pygarmin.exe\__main__.py", line 7, in <module>
  File "C:\Users\AME\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygarmin\pygarmin.py", line 1522, in main
    command(args)
  File "C:\Users\AME\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygarmin\pygarmin.py", line 459, in put_tracks
    gpx = GPX.GarminTracks(args.filename, datatypes)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AME\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygarmin\gpx.py", line 1017, in __init__
    self.tracks = self.gpx_to_tracks(xml_or_file, datatypes)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AME\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygarmin\gpx.py", line 1061, in gpx_to_tracks
    trk_point.set_color(color)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'D302' object has no attribute 'set_color'
What can be done?

**Comment by R1BGW** [comment]
C:\Users\AME>pygarmin -p COM6 put-tracks -t gpx  C:\Users\AME\Desktop\после.gpx
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\AME\AppData\Local\Programs\Python\Python312\Scripts\pygarmin.exe\__main__.py", line 7, in <module>
  File "C:\Users\AME\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygarmin\pygarmin.py", line 1520, in main
    app = Pygarmin(args.port)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AME\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygarmin\pygarmin.py", line 236, in __init__
    self.gps = self.get_gps(self.port)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AME\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygarmin\pygarmin.py", line 242, in get_gps
    return mod_garmin.Garmin(phys)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AME\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygarmin\garmin.py", line 144, in __init__
    self.product_data = self.product_data_protocol.get_product_data()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AME\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygarmin\protocol.py", line 174, in get_product_data
    packet = self.link.expect_packet(self.link.pid_product_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AME\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygarmin\protocol.py", line 52, in expect_packet
    raise mod_error.ProtocolError(f"Expected {pid:3}, got {packet['id']:3}")
pygarmin.error.ProtocolError: 'Expected 255, got 249'

**Comment by fvdbeek** [comment]
The error `AttributeError: 'D302' object has no attribute 'set_color'` means that the track transfer protocol of your device doesn't support the setting of colors. In fact, none of them does, only waypoint protocols. The `gpx_to_tracks` method tries to parse all used gpx extensions, including the 'DisplayColor' attribute. The solution would be to edit the gpx file and remove all 'DisplayColor' attributes.
The error `pygarmin.error.ProtocolError: 'Expected 255, got 249'` suggests that your GPS device doesn't use the product data protocol and answers with an undocumented packet ID 249. Probably, you use an unsupported device that doesn't comply with [the official protocol specification](https://www8.garmin.com/support/commProtocol.html).

**Comment by fvdbeek** [comment]
Close inactive issue.
