### ISSUE TITLE
Protocol error with eTrex Venture HC

### ISSUE THREAD

**Issue by S73f4n** [quentinsf/pygarmin#16]
Hi there,
I'm running into this problem when using pygarmin and my old eTrex Venture HC on Ubuntu 24.04 with Python 3.12. Any pygarmin command terminates with the following error. Any help fixing this issue would be appreciated!

`Traceback (most recent call last):
  File "/home/stefan/.venv/bin/pygarmin", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/stefan/.venv/lib/python3.12/site-packages/pygarmin/pygarmin.py", line 1520, in main
    app = Pygarmin(args.port)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/stefan/.venv/lib/python3.12/site-packages/pygarmin/pygarmin.py", line 236, in __init__
    self.gps = self.get_gps(self.port)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stefan/.venv/lib/python3.12/site-packages/pygarmin/pygarmin.py", line 242, in get_gps
    return mod_garmin.Garmin(phys)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stefan/.venv/lib/python3.12/site-packages/pygarmin/garmin.py", line 144, in __init__
    self.product_data = self.product_data_protocol.get_product_data()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stefan/.venv/lib/python3.12/site-packages/pygarmin/protocol.py", line 174, in get_product_data
    packet = self.link.expect_packet(self.link.pid_product_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stefan/.venv/lib/python3.12/site-packages/pygarmin/protocol.py", line 52, in expect_packet
    raise mod_error.ProtocolError(f"Expected {pid:3}, got {packet['id']:3}")
pygarmin.error.ProtocolError: 'Expected 255, got   2'
`

**Comment by fvdbeek** [comment]
The error `'Expected 255, got   2' ` means something goes wrong early in the USB protocol. I never encountered this behavior and Pygarmin doesn't yet support it, but it is documented in the official protocol specification. I could try to fix this but I need your help, because I don't own an eTrex Venture HC. Could you post the output of
```
   pygarmin --debug info
```

**Comment by fvdbeek** [comment]
Close inactive issue.

**Comment by luguenth** [comment]
I had the same Issue, with an old GPSmap 60csx, maybe its completely out of range. But anyways, I thought I'll provide the debug log for the same Error:

```
Version 2.0.3
2025-09-07 14:07:03,799 Version 2.0.3
Start USB session
2025-09-07 14:07:03,821 Start USB session
Send Start Session packet
2025-09-07 14:07:03,822 Send Start Session packet
Pack packet
2025-09-07 14:07:03,822 Pack packet
Data size: 0
2025-09-07 14:07:03,822 Data size: 0
< packet 5:
2025-09-07 14:07:03,822 < packet 5:
Read Session Started packet
2025-09-07 14:07:03,822 Read Session Started packet
> 00 00 00 00 06 00 00 00 04 00 00 00 05 25 f2 d2
2025-09-07 14:07:03,824 > 00 00 00 00 06 00 00 00 04 00 00 00 05 25 f2 d2
Received Session Started packet
2025-09-07 14:07:03,824 Received Session Started packet
Listening on port usb:
2025-09-07 14:07:03,824 Listening on port usb:
Request product data...
2025-09-07 14:07:03,824 Request product data...
Pack packet
2025-09-07 14:07:03,824 Pack packet
Data size: 0
2025-09-07 14:07:03,824 Data size: 0
< 14 00 00 00 fe 00 00 00 00 00 00 00
2025-09-07 14:07:03,824 < 14 00 00 00 fe 00 00 00 00 00 00 00
Expect product data
2025-09-07 14:07:03,824 Expect product data
> 00 00 00 00 02 00 00 00 00 00 00 00
2025-09-07 14:07:03,826 > 00 00 00 00 02 00 00 00 00 00 00 00
Traceback (most recent call last):
  File "/home/***/.local/bin/pygarmin", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/***/.local/share/pipx/venvs/pygarmin/lib/python3.13/site-packages/pygarmin/pygarmin.py", line 1520, in main
    app = Pygarmin(args.port)
  File "/home/***/.local/share/pipx/venvs/pygarmin/lib/python3.13/site-packages/pygarmin/pygarmin.py", line 236, in __init__
    self.gps = self.get_gps(self.port)
               ~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/***/.local/share/pipx/venvs/pygarmin/lib/python3.13/site-packages/pygarmin/pygarmin.py", line 242, in get_gps
    return mod_garmin.Garmin(phys)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/***/.local/share/pipx/venvs/pygarmin/lib/python3.13/site-packages/pygarmin/garmin.py", line 144, in __init__
    self.product_data = self.product_data_protocol.get_product_data()
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/***/.local/share/pipx/venvs/pygarmin/lib/python3.13/site-packages/pygarmin/protocol.py", line 174, in get_product_data
    packet = self.link.expect_packet(self.link.pid_product_data)
  File "/home/***/.local/share/pipx/venvs/pygarmin/lib/python3.13/site-packages/pygarmin/protocol.py", line 52, in expect_packet
    raise mod_error.ProtocolError(f"Expected {pid:3}, got {packet['id']:3}")
pygarmin.error.ProtocolError: 'Expected 255, got   2'
```
